use_frameworks!

platform :ios, '9.0'

target 'ADAlertControllerForSwift_Example' do
  pod 'ADAlertControllerForSwift', :path => '../'

  target 'ADAlertControllerForSwift_Tests' do
    inherit! :search_paths

    
  end
end
